version: "3.8"
services:
  db:
    image: postgres:15
    container_name: ais_postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  listener:
    build: ./listener
    container_name: ais_listener
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: $DATABASE_URL
      AIS_HOST: $AIS_HOST
      AIS_PORT: $AIS_PORT
    volumes:
      - ./listener:/app
      - ./utils:/app/utils
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python", "listener.py"]

  dispatch:
    build: ./dispatch
    container_name: ais_dispatch
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: $DATABASE_URL
      REMOTE_SERVER_ADDRESS: $REMOTE_SERVER_ADDRESS
      REMOTE_SERVER_USER: $REMOTE_SERVER_USER
      REMOTE_SERVER_PW: $REMOTE_SERVER_PW
    volumes:
      - ./dispatch:/app
      - ./utils:/app/utils
    command: ["python", "dispatch.py"]

  config_ui:
    build: ./ui
    container_name: ais_ui
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - "5000:5000"
    volumes:
      - ./ui:/app
      - ./utils:/app/utils
    command: ["python", "app.py"]

volumes:
  postgres_data:
